# Generated by Django 5.0.6 on 2024-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirm_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
